# Generated by Django 4.2.16 on 2025-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('plays', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'artist',
            },
        ),
    ]
