# Generated by Django 4.2.16 on 2025-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='audio/songs/'),
        ),
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
